### ISSUE TITLE
Graphic stutters

### ISSUE THREAD

**Issue by erasam** [flightsimcloud/advanced-vfr-map#9]
I have installed Advanced VFR Map that I consider really a valuable addon for MSFS

Unfortunately on my mid-level PC (considering MSFS requirements) after the installation I started to have really disturbing stutters

Trying to tune graphics settings didn't help a lot (actually I have earned a couple of FPS neverthless) therefore I uninstalled the addon and the stuttests disappeared

**Comment by toorop** [comment]
This feature use ressources, so when you use it it's normal that you have less ressources for the simulator.
You can try to minimise the panel and display the map (and follow your plane) via he web version on another device.

**Comment by FallenPudding** [comment]
Although this is an excellent addon for FS2020 the frame stutters are present on my system (a high end one). For whatever reason (and I doubt it's system resources) this addon causes frame stuttering even when monitoring on a secondary device. It's a shame but in it's current state it is not useable.

**Comment by toorop** [comment]
> in it's current state it is not useable.

So don't use it.

**Comment by FallenPudding** [comment]
what a great answer dude, you clearly have very little idea what you're doing from a technical standpoint because something like this should not create i game stuttering, it's not using that much resource. Another VFR map plugin works without causing any stutters. But you keep being you, don't learn, don't get better just keep on muttering. Don't bother replying, I will never read it.
